name: Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: jodersky/setup-mill@v0.2.3
        with:
          mill-version: 0.9.9
      - name: Test
        run: make test

  check_format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: jodersky/setup-mill@v0.2.3
        with:
          mill-version: 0.9.9
      - name: Check Format
        run: make checkformat

  all_tests_passed:
    name: "all tests passed"
    needs: [test, check_format]
    runs-on: ubuntu-20.04
    steps:
      - run: echo Success!